[package]
name = "convolution_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.12.0"
mnist = "0.6.0"
ndarray = "0.15.6"
tqdm = "0.6.0"